SET NOCOUNT ON

DECLARE @Table varchar(50) = 'Workout'

SELECT  c.TABLE_NAME,
		c.COLUMN_NAME,
		c.DATA_TYPE,
		c.CHARACTER_MAXIMUM_LENGTH,
		c.NUMERIC_PRECISION,
		c.IS_NULLABLE,
		CASE WHEN EXISTS(select * from information_schema.KEY_COLUMN_USAGE kcu WHERE kcu.TABLE_NAME = @Table AND kcu.COLUMN_NAME = c.COLUMN_NAME AND LEFT(CONSTRAINT_NAME,3) = 'PK_') THEN 1 ELSE 0 END AS COLUMN_PRIMARY_KEY,
		c.ORDINAL_POSITION,
		';' AS EOL
FROM INFORMATION_SCHEMA.COLUMNS c
WHERE c.TABLE_NAME = @Table

